### PR TITLE
Remove unneeded --progress flag from borg create. See borg#7334

### PR DESCRIPTION
**Pull request by m3nu**
See https://github.com/borgbackup/borg/pull/7334

### CODE REVIEW

**Comment by RayyanAnsari** [comment]
Fixes my issue shown in the screenshot here: https://github.com/borgbase/vorta/discussions/1590#discussion-4841816

**Comment by m3nu** [comment]
Even better! It will also be needed, once this change is merged in Borg.

**Review by real-yfprojects — CHANGES_REQUESTED** [review]
I don't think this is the way to go. See https://github.com/borgbackup/borg/pull/7334#issuecomment-1426683747

**Comment by real-yfprojects** [comment]
@m3nu close this?

**Comment by m3nu** [comment]
Right, good find. Not needed any more.

**Pull request closed without merging**
