### PR TITLE
add exclude patterns for most common media files and .part files

### PR DESCRIPTION
**Pull request by renner0e**
adds more exclusion presets related to media files, video and audio.
No picture formats because they were not added the originally

Does it make sense to split them up in music, video and images in the future?
Possibly make a new file for just media formats as they are now in dev.json
### How Has This Been Tested?

~~I did not test anything~~
json is valid
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Review by m3nu — DISMISSED** [review]

**Comment by m3nu** [comment]
Thanks for the contribution! Wanna move them to a separate file and make the groups you suggested? Could be nice, I think. `dev` was imagined for code tools, git cache and such.

**Comment by renner0e** [comment]
> Thanks for the contribution! Wanna move them to a separate file and make the groups you suggested? Could be nice, I think. `dev` was imagined for code tools, git cache and such.

Should I do that in this PR or in a later PR?

Did you intend to make a merge commit on my branch? Instead of merging it into main branch?

**Comment by m3nu** [comment]
I would do it in the same PR, since it's a small change.

I've rebased your branch to include the latest changes.

**Review by m3nu — APPROVED** [review]
Looks good to me.

**Comment by m3nu** [comment]
Thanks for the change and contribution. Looks all good. Anything to add before merging?

**Comment by renner0e** [comment]
> Thanks for the change and contribution. Looks all good. Anything to add before merging?

It's fine

**Pull request merged**
