### PR TITLE
Add a button to mount whole repository.

### LINKED ISSUE #1256: Feature request: mount repository
Borg allows mounting of the whole repository as a FUSE filesystem, in which all archives are shown as directories. This may be useful if you're looking for something specific, want to do diff between different versions of the same file etc. Vorta seems to currently only support mounting of the individual archives and repo mount can be achieved only via command-line.

### PR DESCRIPTION
**Pull request by real-yfprojects**
Fixes #1256.

* src/vorta/assets/UI/archivetab.ui : Rename `bMount` to `bMountArchive`.

* src/vorta/assets/UI/archivetab.ui : Add `bMountRepo`.

* src/vorta/views/archive_tab.py (ArchiveTab): Rename `bMount` to `bMountArchive`.

* src/vorta/views/archive_tab.py (ArchiveTab): Implement behaviour for `bMountRepo`.
	Add `repo_mount_point` attribute.

* src/vorta/views/archive_tab.py (ArchiveTab): Add tooltips to `bMountArchive`.

* src/vorta/views/archive_tab.py (ArchiveTab): Adjust `mount_action` and `unmount_action` to
	mount and unmount the full repository as well.

* src/vorta/utils.py (get_mount_points): Also search for full repo mounts.

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Can someone test mounting? On my VM the file chooser always emitted the signal that mounting is connected to twice for some reason.

**Comment by real-yfprojects** [comment]
This is how it looks. The order of the buttons beneath the archive list can be changed.

mountrepo

**Comment by m3nu** [comment]
Looks good. Just need to run it locally for testing. 👍

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Works well. Thanks for fixing!

**Pull request merged**
