### PR TITLE
Link contributors and translators

### PR DESCRIPTION
**Pull request by m3nu**

### CODE REVIEW

**Comment by m3nu** [comment]
Decided to not add a long list directly, but just links. Looks alright to me.

Preview: https://github.com/m3nu/vorta/tree/pull/add-contributor-credits

**Comment by ThomasWaldmann** [comment]
Link from changeset: https://github.com/borgbase/vorta/graphs/contributors

**Comment by ThomasWaldmann** [comment]
https://www.transifex.com/borgbase/teams/95318/de/ that looks strange.

**Comment by m3nu** [comment]
I added you as coordinator. It doesn't show project-level members by default. It's not perfect, but it will stay updated. I'd prefer some stats on who entered how many translations, etc.

**Comment by m3nu** [comment]
Alternatively I'll link to the translation issue #159 and keep that updated.

**Pull request merged**
