### PR TITLE
Fix kwallet again

### PR DESCRIPTION
**Pull request by samuel-w**
One last try to fixing kwallet. If this doesn't work just remove the kwallet code, its causing more bugs than solutions.

Slightly based it off python-keyring's implementation, https://github.com/jaraco/keyring/blob/main/keyring/backends/kwallet.py#L96.

### CODE REVIEW

**Comment by samuel-w** [comment]
Wait, why don't we just use python-keyring?

**Comment by m3nu** [comment]
Doesn't change the functionality of the code, right? Just re-arranges a few things.

**Comment by m3nu** [comment]
> Wait, why don't we just use python-keyring?

We did in the beginning, but there were other issues, like Pyobjc segfaults.

https://github.com/borgbase/vorta/issues/190#issuecomment-463037623

**Comment by m3nu** [comment]
Thanks, cherry-picked a change into #898.

**Pull request closed without merging**
