### PR TITLE
Add KWallet support

### LINKED ISSUE #236: Support KDE KWallet
We have already implemented macOS Keychain and Gnome Keyring to store passwords. KWallet should be added next.

Some inspiration:

- https://gist.github.com/eberle1080/1304965
- https://stackoverflow.com/questions/2147724/using-kwallet-in-pyqt4

### PR DESCRIPTION
**Pull request by samuel-w**
In the future, we should check if the wallet closes in between detecting the current keyring and setting the password.

Also, is there an alternate way to do keyring detection other than a mountain of try excepts? The code is starting to get hard to read.

Fixes #236

### CODE REVIEW

**Comment by samuel-w** [comment]
Wait, QtDBus exists. Have to change code

**Comment by samuel-w** [comment]
Attempting to port to QtDBus, unsucessful.
Python crashes with "No such method 'open' in interface 'org.kde.KWallet' at object path '/modules/kwalletd5' (signature 'sis')"
Even when I convert the wId to qlonglong, it still gets converted back to an int.
However, the existing dbus code still works.
https://gist.github.com/samuel-w/005453d30250265e2c75c167d9b545b3

**Comment by Hofer-Julian** [comment]
Too bad...
But thanks for trying :)

**Comment by samuel-w** [comment]
Tested and it works, woohoo. Had to use command line to get the handle.

**Comment by m3nu** [comment]
Dont want to add this any more? I’m a bit behind merging PRs due to many other things going on, but plan to catch up over Aug.

**Comment by rejinka** [comment]
I really would like to get this feature

**Comment by samuel-w** [comment]
Initially closed this because I thought no one would use it, as more code = more maintenance. Guess I was wrong.

**Review by m3nu — DISMISSED** [review]

**Comment by samuel-w** [comment]
Wait a bit, I may have forgot to catch an exception

**Comment by samuel-w** [comment]
Turns out there is no uncaught exception, but I did find a bug #606

**Comment by samuel-w** [comment]
What's the status of this?

**Review by m3nu — APPROVED** [review]

**Comment by rejinka** [comment]
Thank you very much @samuel-w and @m3nu!

**Pull request merged**
