### PR TITLE
Add confirmation dialog when deleting a profile.

### LINKED ISSUE #222: Add a confirmation pop-up before actually deleting a profile
Clicking the trashbin icon immediately deletes the shown profile, I (very in favour of minimal clicks...) prefer to have here a "Are you really sure to delete the profile...?" question here before actually deleting:

grafik

### PR DESCRIPTION
**Pull request by bsvh**
This fixes #222.

### CODE REVIEW

**Comment by m3nu** [comment]
Thanks. I'll look into this for the next release. We may already have a wrapper for the messagebox that could be used.

But this feature is surely needed.

**Comment by sudwhiwdh** [comment]
What does it take from your side to solve this open issue?

**Comment by m3nu** [comment]
> What does it take from your side to solve this open request?

We can probably merge it after resolving the conflicts.

**Comment by sudwhiwdh** [comment]
Looks like the Travis CI build passed. So what conflicts are you referring to exactly?

**Comment by m3nu** [comment]
Yes, that conflict.

**Comment by m3nu** [comment]
Merged after resolving minor conflict.

**Pull request closed without merging**
