### PR TITLE
Implement QtSingleApplication

### PR DESCRIPTION
**Pull request by Hofer-Julian**
This implements similar functionalites as [QtSingleApplication](https://github.com/qtproject/qt-solutions/tree/master/qtsingleapplication) (adapted from https://stackoverflow.com/a/12712362/11038610) which unfortunately is not available for Python.

It solves part of https://github.com/borgbase/vorta/issues/132 and enables work on https://github.com/borgbase/vorta/issues/233.

In theory it should work on all Linux distributions, macOS and Windows.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
@m3nu if this works on macOS it should be okay to merge this pull request :)

**Comment by m3nu** [comment]
Fully agree. I just take some more time testing new PRs after the flood of hotfixes I had to do recently.

**Comment by Hofer-Julian** [comment]
Completely understandable. Can I do more to help, apart from have it running on my machine?

(I am also currently looking into writing tests for the other functions I implemented)

**Comment by m3nu** [comment]
I can confirm that your change works as promised on macOS and Ubuntu 18.04.

Also thanks for the offer. Since you're already maintainer, you can just jump on anything you see. Like better tests. Some issues are just dependent on the environment and hard to test.

**Comment by Hofer-Julian** [comment]
> Some issues are just dependent on the environment and hard to test.

Some issues seemed to be KDE specific. I also noticed that vorta sometimes responds differently under Wayland than it does under X. Is it be possible to set up two Linux environments under Travis? Like Kubuntu 18.04 with KDE and X and Fedora 29 with GNOME and Wayland?

**Pull request merged**
