### PR TITLE
fix "Tests leave key in keyring", #1215

### PR DESCRIPTION
**Pull request by swapnil290502**
#1215  solved
removed key from keyring

### CODE REVIEW

**Comment by swapnil290502** [comment]
please review this

**Comment by m3nu** [comment]
Thanks for the contribution!

I don't think this is what you want. It just breaks sorting keyrings.

To remove saved passwords after testing, you'll want to adjust our tests here: https://github.com/borgbase/vorta/tree/master/tests

Pytest fixtures can probably be used to make a helper that cleans up after itself. Maybe this was already solved elsewhere.

You'll also want to run our tests before opening a PR. They should all pass. This includes code formatting and functiona l tests.

Any other questions, we're here to help.

**Comment by swapnil290502** [comment]
I am newbie to contribution I don't know how to contribute . Can you tell
me ?
I have good commands in Python and C++
with strong grasp in data structures and algorithms.


Can you suggest me few tips ...?

**Comment by real-yfprojects** [comment]
> I am newbie to contribution I don't know how to contribute 

Are you familiar with the basics of using git?
This would be the first step. Then setup you development environment as described [in our guide](https://vorta.borgbase.com/contributing/). After that you can start coding.

I would start with adding a `remove_password(self, service, repo_url)` method to the abstract `VortaKeyring` and implementing that method in the subclasses `VortaDarwinKeyring`, `VortaDBKeyring`, `VortaSecretStorageKeyring` and `VortaKWallet5Keyring`. After that I would commit these changes. I would then write a second commit adjusting the tests to use the new method for removing keys they have created. We use `pytest` for testing. Make sure to read into how that works before this step.

**Comment by real-yfprojects** [comment]
Closing in favor of #1639

**Pull request closed without merging**
