### PR TITLE
V0.6.3

### PR DESCRIPTION
**Pull request by m3nu**

### CODE REVIEW

**Comment by bjo81** [comment]
Hm, the v0.6.3 tag is missing.

**Comment by m3nu** [comment]
> Hm, the v0.6.3 tag is missing.

Pushed.

**Comment by m3nu** [comment]
I only made half a release yesterday to get 2 bug fixes out. But didn't push the tags and macOS release. Will be sure to always add the tag in the future.

**Comment by bjo81** [comment]
Thanks, updated AUR.

**Comment by m3nu** [comment]
If this update step can somehow be automated, we should do it. Though there will be fewer updates in the future I guess.

**Pull request merged**
