### PR TITLE
Fix issue 1564

### PR DESCRIPTION
**Pull request by herrwusel**
I think the issue #1564 is fixed just by changing the version check. I tested it locally and archives are getting pruned as intended.

### CODE REVIEW

**Comment by m3nu** [comment]
Thanks for the report and quick fix!

Though I'm afraid the command is correct and maybe your repo doesn't have archives due for pruning or the wrong prefix. I tested pruning manually before the release and it worked as expected. Based on the latest docs, the command is correct too.

https://borgbackup.readthedocs.io/en/stable/usage/prune.html

Your commit simply disables setting any prefix for Borg 1.x, which would be pretty dangerous and unexpected for users. 😬

**Comment by herrwusel** [comment]
Oh, I see what you mean. Still I observed the following:
- I built from the master branch and one repo which has archives to be pruned didn't get pruned.
- I switched to my patch branche and said archives got pruned. 

master:
```
2023-01-24 19:07:41,182 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg prune --list --info --log-json --keep-hourly 1 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 -a sh:c940-arch-* --keep-within 10H user@target:/path/to/backup/
2023-01-24 19:07:42,767 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 5
2023-01-24 19:07:42,767 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 5
```
patch branch:
```
2023-01-24 19:10:34,545 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg prune --list --info --log-json --keep-hourly 1 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 --prefix myprefix --keep-within 10H user@target:/path/to/backup/
2023-01-24 19:10:34,724 - vorta.borg.borg_job - WARNING - Warning: "--prefix" has been deprecated. Use "--glob-archives 'yourprefix*'" (-a) instead.
2023-01-24 19:10:35,933 - vorta.borg.borg_job - INFO - Keeping archive (rule: within #1):       myprefix2023-01-24-150403-04       Tue, 2023-01-24 15:04:07 [b722a97793d631308a36d8e0cb48a51087ec48ecbc513c1fdb28ae3a895b44c4]
2023-01-24 19:10:35,933 - vorta.borg.borg_job - INFO - Keeping archive (rule: hourly #1):       myprefix2023-01-24-090115-04       Tue, 2023-01-24 09:01:20 [f3011a829ebe2ee4b2bc0589f457ff0b93c7789f093dcbb12937a7a88b33444a]
2023-01-24 19:10:35,934 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #1):        myprefix2023-01-23-201546-04       Mon, 2023-01-23 20:15:51 [ed9fbd469ef83f3babbc08e8b0b2996efade8e9e5d4f53451d63e1a1d39633aa]
2023-01-24 19:10:45,581 - vorta.borg.borg_job - INFO - Pruning archive (1/5):                   myprefix2023-01-23-141157-04       Mon, 2023-01-23 14:11:59 [06d7b785a964a1b5f461a246ab0543daf883c8cf9e077ddd3ec3befbd4b81e78]
2023-01-24 19:10:54,774 - vorta.borg.borg_job - INFO - Pruning archive (2/5):                   myprefix2023-01-23-080919-04       Mon, 2023-01-23 08:09:23 [aa0bd57c16c1da898af6f5344102f25eca1bbf92e13131c5d1680e8ca56f9ef0]
2023-01-24 19:10:54,775 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #2):        myprefix2023-01-22-193214-03       Sun, 2023-01-22 19:32:19 [c4e37131f58fd5e1f596761acbd75c237b0ddf2a0027e2067f076cde47d2d71f]
2023-01-24 19:11:04,446 - vorta.borg.borg_job - INFO - Pruning archive (3/5):                   myprefix2023-01-22-080736-03       Sun, 2023-01-22 08:07:41 [135056bb2a140c0c4be54a651bfcc396fa7593a2eb99781316e31e43bc148b08]
2023-01-24 19:11:04,447 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #3):        myprefix2023-01-21-190328-03       Sat, 2023-01-21 19:03:33 [9b37885d914e0d25956cfa043c7fd2034ae73cfb322b221f67e8280ee5489d8c]
2023-01-24 19:11:04,447 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #4):        myprefix2023-01-20-203817-03       Fri, 2023-01-20 20:38:21 [309a388a101ff93efd6e6479db8b7639f26e76e8037665098aa69249706c6a1c]
2023-01-24 19:11:04,449 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #5):        myprefix2023-01-19-203242-03       Thu, 2023-01-19 20:32:46 [a94bd76b5a7be130742c8d5f0dd26d1103f4f32ad8e69c2eb7fac034a7308ccc]
2023-01-24 19:11:04,449 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #6):        myprefix2023-01-18-203257-03       Wed, 2023-01-18 20:33:01 [009fdf0b9c37deb54ff034c1603a3aca44a552ea7de03b7af5f29754c6b3e6e0]
2023-01-24 19:11:04,449 - vorta.borg.borg_job - INFO - Keeping archive (rule: daily #7):        myprefix2023-01-17-202108-03       Tue, 2023-01-17 20:21:13 [c7e574e2c6f4e59902b3c0f0a394a1f0d720dea22b13e1f7b28f11069c360eae]
2023-01-24 19:11:14,430 - vorta.borg.borg_job - INFO - Pruning archive (4/5):                   myprefix2023-01-16-192625-03       Mon, 2023-01-16 19:26:28 [7cb928f2a6ad2de85d24596dcc106537a8651b4439340808b02437a4a2f6464a]
2023-01-24 19:11:14,431 - vorta.borg.borg_job - INFO - Keeping archive (rule: weekly #1):       myprefix2023-01-15-223331-02       Sun, 2023-01-15 22:33:34 [0bb42a516aaf083508025ae2ce081cee9c2079d36e1da827f33fd5933090f90b]
2023-01-24 19:11:14,433 - vorta.borg.borg_job - INFO - Keeping archive (rule: weekly #2):       myprefix2023-01-08-210451-01       Sun, 2023-01-08 21:04:56 [9389f3e63344189c221e201b226ba9a424e1b2eb000011293038ccbc9aee4701]
2023-01-24 19:11:14,433 - vorta.borg.borg_job - INFO - Keeping archive (rule: weekly #3):       myprefix2023-01-01-174508-52       Sun, 2023-01-01 17:45:14 [265ae266a556e423121694a1f936866380f55db3ae7de162d3bd11b3549de2c1]
2023-01-24 19:11:14,439 - vorta.borg.borg_job - INFO - Keeping archive (rule: weekly #4):       myprefix2022-12-21-203445-51       Wed, 2022-12-21 20:34:50 [78959b16fbaf3023083f3e627c757d78e95413d7be2e15fcd292cc62b244cd8b]
2023-01-24 19:11:25,208 - vorta.borg.borg_job - INFO - Pruning archive (5/5):                   myprefix2022-12-18-211243-50       Sun, 2022-12-18 21:12:48 [054fa077edd04a91a79245644ff787bbadad9168a71aed5f49a3f4d5587cdd18]
2023-01-24 19:11:25,209 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #1):      myprefix2022-11-30-210603-48       Wed, 2022-11-30 21:06:08 [7bb6f02db6e299e2c706935a8377ec1096f79cadb2bbd5dac967872d31a7bd5c]
2023-01-24 19:11:25,209 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #2):      myprefix2022-10-31-165221-44       Mon, 2022-10-31 16:52:26 [3619111a84e0c03d9f116d9bc48d99cb11a886db54faf1b1aa95289b0b8cc887]
2023-01-24 19:11:25,211 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #3):      myprefix2022-09-30-185141-39       Fri, 2022-09-30 18:51:46 [2f1485d17ac4e2a16f3919a843abe4345fd9df5ee6cc8de84c71a475cedc9124]
2023-01-24 19:11:25,211 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #4):      myprefix2022-08-29-132025-35       Mon, 2022-08-29 13:20:27 [04c8c9c103f9ea875edeac5c37537274bfa81ccf385b7d835dcec5922bdc17e3]
2023-01-24 19:11:25,211 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #5):      myprefix2022-07-31-184550-30       Sun, 2022-07-31 18:45:56 [85a25ddd3e2bbb2b85f1f9e69a025d8bce29565d9ba06d3a87b93beb0d347c6e]
2023-01-24 19:11:25,211 - vorta.borg.borg_job - INFO - Keeping archive (rule: monthly #6):      myprefix2022-06-30-132430-26       Thu, 2022-06-30 13:24:35 [24129899d32b77d53c0d2e82c6b44e876ed9fac2f529c17bddd0c100f6a4c347]
2023-01-24 19:11:25,213 - vorta.borg.borg_job - INFO - Keeping archive (rule: yearly[oldest] #1): myprefix2022-03-18-132013          Fri, 2022-03-18 13:20:17 [cc99fa5ee7858614d5848ed8be62716dcf144a0f5d867625f9203892d45c94f0]
2023-01-24 19:12:23,175 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 5
2023-01-24 19:12:23,176 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 5
```

I think only the prefix `sh:` is messing up pruning for me. I can still use prune with `-a` option when I remove the `sh:` by manually copying the vorta commands into console. Maybe the server side borg version is causing trouble? It is on version 1.1.16 (bullseye stable).

**Comment by real-yfprojects** [comment]
I stumbled upon this line when merging #1392. I thought, that specifying the pattern format wouldn't hurt for borg v1.2.2 eliminating the need for an additional if statement. However this line in the [changelogs of borg](https://borgbackup.readthedocs.io/en/2.0.0b4/changes.html#change-log) confirm that different archive glob patterns aren't supported:

> the --glob-archives option was renamed to --match-archives (the short option name -a is unchanged) and extended to support different pattern styles:
>
>    id: for identical string match (this is the new default!)
>    sh: for shell pattern / globbing match (this was used by --glob-archives)
>    re: for regular expression match

We therefore need different behaviour for borg <1.2.2, >=1.2.2 and >= 2.0.0.

**Comment by m3nu** [comment]
Like this?

```
if borg_compat.check('V2'):
    pruning_opts += ['-a', f"{formatted_prune_prefix}*']
elif borg_compat.check('V122'):
    pruning_opts += ['-a', f"sh:{formatted_prune_prefix}*"]
else:
    pruning_opts += ['--prefix', formatted_prune_prefix]
```

**Comment by herrwusel** [comment]
On my system with `1.2.3` the `sh:` is not working. To my understanding:
```
if borg_compat.check('V2'):
    pruning_opts += ['-a', f"sh:{formatted_prune_prefix}*']
elif borg_compat.check('V122'):
    pruning_opts += ['-a', f"{formatted_prune_prefix}*"]
else:
    pruning_opts += ['--prefix', formatted_prune_prefix]
```

**Comment by real-yfprojects** [comment]
the latter

**Review by m3nu — APPROVED** [review]

**Review by real-yfprojects — APPROVED** [review]

**Comment by real-yfprojects** [comment]
Thank you @herrwusel for your work!

**Pull request merged**
