### PR TITLE
Sort archive sizes in archive tab

### PR DESCRIPTION
**Pull request by samuel-w**

### CODE REVIEW

**Comment by m3nu** [comment]
So this allows sorting by size or always sorts by size?

**Comment by samuel-w** [comment]
It sorts by size correctly. Before it alphabetically sorted the size strings leading to the wrong result.

**Comment by samuel-w** [comment]
Also it pushes the empty rows to the bottom when sorting descendingly, and pushes them to the top when sorting ascendingly

**Comment by m3nu** [comment]
I think the sorting should be by date by default since this is how Borg sorts. By size isn't meaningful.

Sorting by alphabet was an approximation of date-based sorting. Maybe not fully correct, so I'm open to improve on that. By size doesn't make sense, since I will generally look for an archive done on a specific day. I really don't care about the size. I just want my data back on a specific day.

Of course sorting using other columns could be possible too and there may be a case where size is useful.

**Comment by samuel-w** [comment]
This doesn't change the sorting behaviour of anything else. It just makes the sizes sort correctly.
Before:
Before
After:
After

**Comment by m3nu** [comment]
Great. That was my question before. If you fixed sorting by size, that's perfect.

**Review by m3nu — APPROVED** [review]

**Pull request merged**
