### PR TITLE
Backup settings.db before migrations

### LINKED ISSUE #1641: Create backup of db before migrations.
In case of migrations create a backup copy of the database beforehand. This can easily be achieved by copying the file to the same location but a different file name like `settings.db.bak`.

### PR DESCRIPTION
**Pull request by AdwaitSalankar**
### Description
Creates a backup copy of settings.db before migrations

### Related Issue
Fixes #1641

### How Has This Been Tested?
Tested by creating a copy on `init_db()`

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Thank you very much. This is a useful addition! You can ignore the MacOS tests failing, however the lint workflow should pass. You can use [pre-commit](pre-commit.com) for that as our [contribution docs ](https://vorta.borgbase.com/contributing/) describe. After installing it, you can run `pre-commit --all-files` to also format changes already committed.

**Comment by AdwaitSalankar** [comment]
@real-yfprojects I have made the changes.

**Review by real-yfprojects — APPROVED** [review]

**Comment by m3nu** [comment]
Minor idea: How about we add the `SCHEMA` version to the backup, so we have one backup per migration?

**Comment by AdwaitSalankar** [comment]
@m3nu Does this name look good?
 `settings_v22.db.bak`

**Comment by m3nu** [comment]
Yes. Looks good and we'll have a backup of each migration.

**Comment by AdwaitSalankar** [comment]
@m3nu I have made the changes

**Comment by m3nu** [comment]
We could maybe drop the `.bak` extension and keep `.db` since the name will be different.

And how about adding the datetime (`2023-12-06-142501`) too? If this feature is for devs, I may do the same migration multiple times.

**Comment by m3nu** [comment]
Looks good to me.

**Review by real-yfprojects — APPROVED** [review]

**Comment by CouldBeThis** [comment]
Hi thanks for teaching Vorta how to back itself up! I just made use of it. :)  And I made some quick documentation of how to restore in #1895. Just based on what I read in other threads; hopefully on the right track.

It's probably too late to change it now but would just like to say that including something like `bak` in the filename would actually be more helpful to me as end user. Because then I could know it was a backup.  With a filename like `settings_v20_2024-01-13-195827.db` I would never guess.

**Comment by m3nu** [comment]
Yeah, we could call it `settings-backup-xxx.db`. I wouldn't change the file extension, since the type of file is still the same.

**Pull request merged**
