### PR TITLE
Use native threading module in job_manager

### LINKED ISSUE #1091: Increase test timeout when quitting pending jobs
```
        yield
        # qapp.backup_cancelled_event.emit()
>       qtbot.waitUntil(lambda: not vorta.borg.job_scheduler.JobsManager.is_worker_running())
E       pytestqt.exceptions.TimeoutError: waitUntil timed out in 5000 milliseconds

tests/conftest.py:76: TimeoutError
```

### LINKED ISSUE #1094: Segmentation error with Python 3.10
Segmentation error when trying to start Vorta.

- OS: Fedora 35 Gnome 41
- Vorta version: 0.7.8
- Borg: 1.1.17
- Installed from: repo or pip

Logs:

```
$ vorta
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
2021-11-02 14:50:36,741 - vorta.i18n - DEBUG - Loading translation succeeded for ['nl-BE', 'nl-Latn-BE'].
2021-11-02 14:50:36,744 - apscheduler.scheduler - INFO - Scheduler started
2021-11-02 14:50:36,842 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-11-02 14:50:36,903 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
Segmentatiefout (geheugendump gemaakt)

```

### LINKED ISSUE #1095: Vorta backups are run twice when using scheduled backups
**Describe the bug**
I believe backups are *sometimes* being run twice when using scheduled backups. 

This *sometimes* results in Vorta reporting that a backup did not complete successfully (one of the two duplicate scheduled backups fails).
This *sometimes* results in Vorta creating two backups for the same scheduled backup - these can be seen in the 'Archives' tab .

Screenshot from 2021-11-03 19-23-55

In addition to the above issues, the value for 'Next Backup' in the 'Schedule' tab does not appear to be updated - clearly this is fairly minor.

**To Reproduce**
1. Use the 'Backup every...' facility in the Schedule tab

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: Vorta 0.7.8
- Installed from: Arch AUR - vorta-git. (`pacman -Q vorta-git` outputs `vorta-git r565.fba6a2f-1`)
- Borg: 1.1.17

**Additional context**
I previously used the [vorta](https://aur.archlinux.org/packages/vorta/) AUR package. However, I was affected by #1083 and switched to using [vorta-git](https://aur.archlinux.org/packages/vorta-git/). As such I am running Vorta built from the latest commit - currently `fba6a2f`.

[Vorta logs HERE](https://gist.github.com/DanHam/4ebf7c09811db4cdd66008234b5226d3)

If you need me to run Vorta in debug mode please let me know (and tell me how to do it!). If you need any further info please let me know.

### PR DESCRIPTION
**Pull request by m3nu**
Some cleanup after adding the new jobs scheduler:

- Keep `jobs_manager` with main app
- Rename `job_scheduler` to `jobs_manager` to match main `JobsManager` class
- Remove `if DEBUG` statements. Should use `logger.debug` instead.
- Use native `threading.Thread` class instead of Qt `QThreadpool`
- Remove extra mutex, semaphore, etc.
- Combine `borg.jobs_manager.Job` with `borg.borg_job`

This is a big cleanup. I probably removed too many things. Please let me know if something is broken now or if anything should be put back.

@bastiencyr: Also, my apologies, if this changes much of your earlier PR. I just felt some things could be solved in a simpler way. I still envy the general idea and I'm happy I took the time to understand it in details.

Fixes #1094, fixes #1091, maybe fixes #1095

### CODE REVIEW

**Comment by m3nu** [comment]
So the test are still passing. If I broke anything, we should consider adding a test for that. 😇

**Comment by bastiencyr** [comment]
> @bastiencyr: Also, my apologies, if this changes much of your earlier PR. I just felt some things could be solved in a simpler way. I still envy the general idea and I'm happy I took the time to understand it in details.

I have to admit that Im a little be disappointed but it was necessary 😢😢
Some things was useless like all my prints everywhere, the timeout and some functions like load_from_db. But some important things has been removed (mutex, getters).

**Comment by m3nu** [comment]
Thanks for understanding. My goal is also to help future coders understand it. The main idea of using one queue and worker per repo/site is still there and it was brilliant!

I can put the mutex stuff back. What is it needed for and can we add a test to test for the problem?

**Comment by bastiencyr** [comment]
>     * Combine `borg.jobs_manager.Job` with `borg.borg_job`

I dont think its a good idea. The Job class add an abstraction (interface) and separate jobs manager from jobs itself. By doing this, it becomes difficult to know what jobs managers need (for example a repo_id function, a site_id property...). It will be difficult for another dev to rewrite the jobs manager if needed.

**Comment by m3nu** [comment]
> Its not a good idea. The Job class add an abstraction (interface) and separate jobs manager from jobs itself.

OK. Undoing again. Also looking at locks real quick.

**Comment by m3nu** [comment]
Put back your JobInterface, so it's all in one place.

And added some locks and checks to avoid dupe jobs.

Please help improve, so we get a good PR.

**Comment by bastiencyr** [comment]
Sorry @m3nu , I have an hackathon this week end so basically more than 20 hours of code 😅 
I will tried to help the evening but it it can wait a little, its better 🙄

**Comment by m3nu** [comment]
No worries. All the best for the hackathon! I value your opinion and feedback, so will just keep it open here.

**Comment by bastiencyr** [comment]
Hello @m3nu I look at this today !

**Comment by bastiencyr** [comment]
Is there something else you need @m3nu ? 
I let some comments

**Pull request merged**
