### PR TITLE
change_display_mode() in (views/ )diff_result.py and extract_result.py call to setEnabled instead of setMode

### PR DESCRIPTION
**Pull request by SAMAD101**
### Description

A try at solving the issue #1784 
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Thank you for taking the time to write a pull request. Did you run your code locally and test whether your code changes work?

**Comment by SAMAD101** [comment]
@real-yfprojects yes i've checked by running the code locally.

**Comment by real-yfprojects** [comment]
> yes i've checked by running the code locally.

Well, I get the following error when running your code. At the same time the different display modes like `flat` and `tree` no longer work correctly.

```pytb
2023-09-03 15:30:06,093 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/home/yannick/Programmieren/80_Github/03_Other_Repos/vorta/src/vorta/views/diff_result.py", line 204, in change_display_mode
    self.model.setEnabled(mode)
AttributeError: 'DiffTree' object has no attribute 'setEnabled'
```

You didn't you see that error?

**Comment by SAMAD101** [comment]
> 

https://github.com/borgbase/vorta/assets/71956678/af1780d0-ec5d-498c-9255-23b3aae0ff9a

nope, that error didn't appear in mine

**Comment by real-yfprojects** [comment]
Then you probably didn't ran this branch but some other vorta installation. Did you activate the virtual environment that you installed vorta into using `pip install -e .`? In bash the prompt will start with `(.venv)` or similar when a venv is activated.

**Comment by SAMAD101** [comment]
> Then you probably didn't ran this branch but some other vorta installation. Did you activate the virtual environment that you installed vorta into using `pip install -e .`? In bash the prompt will start with `(.venv)` or similar when a venv is activated.

it was the same branch actually. double checked. no clue why this is happening, will try to look into it

**Pull request closed without merging**
