### PR TITLE
UI Improvements

### PR DESCRIPTION
**Pull request by bastiencyr**
Some variables have to be rename (qtoolbox) but it's ok. Do you like ? 

(edit) Related discussion: https://github.com/borgbase/vorta/discussions/993

### CODE REVIEW

**Comment by m3nu** [comment]
Screenshot and the thinking behind it would be good to discuss this quickly.

**Comment by bastiencyr** [comment]
Yes for sure. 

https://user-images.githubusercontent.com/63359575/122376341-5b472300-cf64-11eb-84a3-d00e0c7d6874.mp4

vorta_gui

**Comment by m3nu** [comment]
I don't hate it. 👍 Needs some getting used to and some work with padding, but more modern and possibly easier to understand. 

What do you think, @Hofer-Julian @ThomasWaldmann ?

*Misc* could be moved to the bottom, since it doesn't just apply to one profile. Like Apple does here with *Login Options*:

**Comment by Hofer-Julian** [comment]
Definitely goes in the right direction in my opinion :)

**Comment by bastiencyr** [comment]
> Misc could be moved to the bottom, since it doesn't just apply to one profile. Like Apple does here with Login Options

Something like that : 
image

**Comment by bastiencyr** [comment]
Hey @m3nu, @ThomasWaldmann , something new here ?

**Comment by m3nu** [comment]
Sorry, didn't see the latest updates. Will test locally.

**Comment by Hofer-Julian** [comment]
@bastiencyr as discussed I've looked into your PR. At the moment your branch crashes with the following error message.

```2022-01-09 17:13:10,856 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: eventlogmodel.end_time

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/job_scheduler.py", line 143, in run
    self.process_jobs()
  File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/job_scheduler.py", line 130, in process_jobs
    job.run()
  File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/borg_job.py", line 212, in run
    log_entry.save()
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 6603, in save
    pk = self.insert(**field_dict).execute()
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 1911, in inner
    return method(self, database, *args, **kwargs)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 1982, in execute
    return self._execute(database)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2761, in _execute
    return super(Insert, self)._execute(database)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2479, in _execute
    cursor = database.execute(self)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3157, in execute_sql
    with __exception_wrapper__:
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: eventlogmodel.end_time
Segmentation fault (core dumped)
```

**Comment by real-yfprojects** [comment]
I don't like the border-less design because the desktop theme picked by the user should decide how to display borders. A Breeze 
user for example will expect the usual breeze borders and the usual breeze non-flat design.

**Comment by bastiencyr** [comment]
> @bastiencyr as discussed I've looked into your PR. At the moment your branch crashes with the following error message.
> 
> ```
> Traceback (most recent call last):
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3160, in execute_sql
>     cursor.execute(sql, params or ())
> sqlite3.IntegrityError: NOT NULL constraint failed: eventlogmodel.end_time
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/job_scheduler.py", line 143, in run
>     self.process_jobs()
>   File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/job_scheduler.py", line 130, in process_jobs
>     job.run()
>   File "/var/home/julian/Projekte/others/vorta/src/vorta/borg/borg_job.py", line 212, in run
>     log_entry.save()
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 6603, in save
>     pk = self.insert(**field_dict).execute()
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 1911, in inner
>     return method(self, database, *args, **kwargs)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 1982, in execute
>     return self._execute(database)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2761, in _execute
>     return super(Insert, self)._execute(database)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2479, in _execute
>     cursor = database.execute(self)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3173, in execute
>     return self.execute_sql(sql, params, commit=commit)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3157, in execute_sql
>     with __exception_wrapper__:
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 2933, in __exit__
>     reraise(new_type, new_type(exc_value, *exc_args), traceback)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 191, in reraise
>     raise value.with_traceback(tb)
>   File "/var/home/julian/Projekte/others/vorta/env/lib64/python3.10/site-packages/peewee.py", line 3160, in execute_sql
>     cursor.execute(sql, params or ())
> peewee.IntegrityError: NOT NULL constraint failed: eventlogmodel.end_time
> Segmentation fault (core dumped)
> ```

Yes, need a rebasing. It will take a moment. I think I need to restart from the beginning.

**Comment by Hofer-Julian** [comment]
@bastiencyr Sure :)

@m3nu are you also interested in this PR?
I can have a look at the code and test it on my Linux machine, but you would still have to test it on macOS.

**Comment by bastiencyr** [comment]
> I don't like the border-less design because the desktop theme picked by the user should decide how to display borders. A Breeze user for example will expect the usual breeze borders and the usual breeze non-flat design.

I understand your concerns and its not an easy problem to tackle. Notice that Breeze still remains close to the flat design (or material but anyway). The style you see is the default provided by qt. But on each platform, when it is possible, qt adds a custom theme (breeze for example). Its difficult to know what will be the final result. In qt designer, you can see different themes (including breeze).

Its very difficult to provide a cross platform native gui. Actually, qt gave up this idea with pyqt.  If you want a real native gui for every platform, you need QML. For now, we can just make compromises.

**Comment by real-yfprojects** [comment]
> The style you see is the default provided by qt. 

It looks like Fusion. But you removed the borders of the list views and the entries.

> Its very difficult to provide a cross platform native gui. Actually, qt gave up this idea with pyqt. If you want a real native gui for every platform, you need QML. For now, we can just make compromises.

On KDE *vorta* and other PyQt apps will not defer from the native look.
There is a *gtk2* style engine for qt that might provide a (near) native look for gnome but I couldn't get it running on my gnome VM. To get *Fusion* looking like a native gnome app will probably need stylesheets but won't come close to the nativity of *vorta* in KDE.

**Comment by bastiencyr** [comment]
> On KDE _vorta_ and other PyQt apps will not defer from the native look. There is a _gtk2_ style engine for qt that might provide a (near) native look for gnome but I couldn't get it running on my gnome VM. 

You might find this information relevant : https://github.com/qt/qtstyleplugins and https://github.com/borgbase/vorta/issues/1023 . As you can see, the native look for gnome has not been updated since 5 years. 

Since, this discussion is part of a more global discussion, we can discuss this on #1050 .

**Pull request closed without merging**
