### PR TITLE
Modify pre-commit config file using autoupdate

### PR DESCRIPTION
**Pull request by ratchek**
### Description
A new version of Poetry broke isort which caused errors when running pre-commit.

Running the command `pre-commit autoupdate` updates the configuration to use the newest isort, which has a hotfix for the bug. It also updates pre-commit, black, and flake8 as a side-effect.

### Related Issue
https://github.com/borgbase/vorta/issues/1600

### Motivation and Context
It fixes the pre-commit checks

### How Has This Been Tested?
I ran pre-commit and it works, when it hasn't before

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Review by real-yfprojects — CHANGES_REQUESTED** [review]
Thanks! Can you lock the black version to 22.*? If pre-commit doesn't allow that, can you adjust the version manually?

**Comment by ratchek** [comment]
Yup. Should I change it to 22.06 (our current version), or 22.12 (the latest 22.* release) ?

**Comment by real-yfprojects** [comment]
> Yup. Should I change it to 22.06 (our current version), or 22.12 (the latest 22.* release) ?

Latest 22.* is fine.

**Review by real-yfprojects — APPROVED** [review]

**Comment by real-yfprojects** [comment]
Thank you! Contributions including such small ones are a great deal.

**Pull request merged**
