### PR TITLE
Pause scheduling for a profile temporarily if a backup fails.

### LINKED ISSUE #1293: Scheduled backup instantly retried on failure - for ever.
**Describe the bug**
Vorta Backup hogs cpu during scheduled backup when access to remote host is not possible.

In my setup vorta uses ssh-agent which in turn is connected to KeePassXC, i.e. identities are only in agent when the wallet is unlocked. The profile schedule is set to backup every 3 hours.

When coming back to the locked machine (and thus locked KeePassXC wallet) vorta often reports `Backup started.` and the message `ERROR: Connection closed by remote host. Is borg working on the server?` appears, vanishes, appears, vanishes … In htop I see `/usr/bin/python /usr/bin/vorta` cycling between 40 to 90+ cpu%. This only happens since the upgrade to 0.8.4. As soon as I unlock the wallet the error message and high cpu usage goes away.

**Not reproducible with manual backup**

I could not yet reproduce the problem with a manually started backup, i.e.:
- if I close the wallet manually and start the backup manually the error appears and stays, no visible cpu usage in this state.
- if I start the backup and lock the wallet during the backup the backup finishes. So I guess the ssh connection to the remote was already established.

**Environment:**
- OS: Arch Linux
- Vorta version: 0.8.4
- Installed from: [AUR](https://aur.archlinux.org/packages/vorta)
- Borg version: 1.2.0

**Additional context**

I guess the [rewrite of the scheduler](https://github.com/borgbase/vorta/pull/1204) somehow introduced this issue.

In the Scheduler -> Log tab I see 10+ entries/minute when the scheduled task starts. It returns with 2. Here is an excerpt from vorta's log file with 2 repetitions of the block that keeps on till 19:36 when the wallet was unlocked and the backup could finish. I did some cleaning of the log to remove ips and so on, hope I was not to zealous.

```
[…]
2022-05-11 19:25:26,164 - vorta.scheduler - INFO - Starting background backup for myprofile
2022-05-11 19:25:26,165 - vorta.notifications - DEBUG - success notifications suppressed
2022-05-11 19:25:26,165 - vorta.keyring.abc - DEBUG - Only available on macOS
2022-05-11 19:25:26,165 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2022-05-11 19:25:26,166 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2022-05-11 19:25:26,166 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo example.com:/path/to/backup
2022-05-11 19:25:26,167 - vorta.scheduler - INFO - Preparation for backup successful.
2022-05-11 19:25:26,168 - vorta.borg.jobs_manager - DEBUG - Add job for site 2
2022-05-11 19:25:26,168 - vorta.borg.jobs_manager - DEBUG - Start job on site: 2
2022-05-11 19:25:26,177 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-if-present .nobackup example.com:/path/to/backup::client-2022-05-11-192526 /home/user/folder/projects /home/user/Documents /home/user/anotherFolder/Documents /home/user/anotherFolder/subfolder
2022-05-11 19:25:26,913 - vorta.borg.borg_job - WARNING - Remote: no such identity: /path/to/a/keyfile: No such file or directory
2022-05-11 19:25:26,914 - vorta.borg.borg_job - WARNING - Remote: remote-user@example-ip: Permission denied (publickey).
2022-05-11 19:25:26,915 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2022-05-11 19:25:27,032 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 2
2022-05-11 19:25:27,033 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 2
2022-05-11 19:25:28,890 - vorta.notifications - DEBUG - notification not suppressed
2022-05-11 19:25:28,911 - vorta.scheduler - ERROR - Error during backup creation.
2022-05-11 19:25:28,912 - vorta.scheduler - INFO - Setting timer for profile 2
2022-05-11 19:25:28,914 - vorta.scheduler - DEBUG - Catching up by running job for myprofile (2)
2022-05-11 19:25:28,915 - vorta.scheduler - INFO - Starting background backup for myprofile
2022-05-11 19:25:28,915 - vorta.notifications - DEBUG - success notifications suppressed
2022-05-11 19:25:28,916 - vorta.keyring.abc - DEBUG - Only available on macOS
2022-05-11 19:25:28,916 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2022-05-11 19:25:28,916 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2022-05-11 19:25:28,917 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo example.com:/path/to/backup
2022-05-11 19:25:28,918 - vorta.scheduler - INFO - Preparation for backup successful.
2022-05-11 19:25:28,918 - vorta.borg.jobs_manager - DEBUG - Add job for site 2
2022-05-11 19:25:28,918 - vorta.borg.jobs_manager - DEBUG - Start job on site: 2
2022-05-11 19:25:28,924 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg create --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-if-present .nobackup example.com:/path/to/backup::client-2022-05-11-192528 /home/user/folder/projects /home/user/Documents /home/user/anotherFolder/Documents /home/user/anotherFolder/subfolder
2022-05-11 19:25:29,658 - vorta.borg.borg_job - WARNING - Remote: no such identity: /path/to/a/keyfile: No such file or directory
2022-05-11 19:25:29,658 - vorta.borg.borg_job - WARNING - Remote: remote-user@example-ip: Permission denied (publickey).
2022-05-11 19:25:29,659 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2022-05-11 19:25:29,774 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 2
2022-05-11 19:25:29,774 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 2
[…]
2022-05-11 19:36:36,619 - vorta.borg.borg_job - INFO - Creating archive at […]
2022-05-11 19:37:06,712 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 2
2022-05-11 19:37:06,713 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 2
2022-05-11 19:37:08,545 - vorta.notifications - DEBUG - success notifications suppressed
2022-05-11 19:37:08,545 - vorta.scheduler - INFO - Backup creation successful.
2022-05-11 19:37:08,546 - vorta.scheduler - INFO - Doing post-backup jobs for myprofile
2022-05-11 19:37:08,547 - vorta.scheduler - INFO - Finished background task for profile myprofile
2022-05-11 19:37:08,548 - vorta.scheduler - INFO - Setting timer for profile 2
2022-05-11 19:37:08,550 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-11 22:37:06.705631
```

### PR DESCRIPTION
**Pull request by real-yfprojects**
Fixes #1293 and #1289.

* src/vorta/scheduler.py (VortaScheduler): Implement `pause` to call a timeout
	on the scheduler for a profile as well as `unpause`.

* src/vorta/scheduler.py (VortaScheduler.notify): Pause/unpause scheduler if a
	backup fails/succeeds.

### CODE REVIEW

**Comment by m3nu** [comment]
Seems like a really complex fix. Wouldn't it be enough to look at where all those repeated jobs are scheduled? And not add all this pause/unpause logic?

**Comment by real-yfprojects** [comment]
> Seems like a really complex fix. Wouldn't it be enough to look at where all those repeated jobs are scheduled?

When triggered the scheduler will find that a backup was missed and immediately start a backup. (If this is disabled in the settings the issue doesn't occur.) The backup will fail and trigger the scheduler again repeating the process. This happens in the `notify` method. One could move the call to `set_timer_for_profile` into the if-block so that it is only executed when the backup succeeds but then the next trigger of the scheduler is undetermined/uncontrolled. It might happen when the user clicks in the GUI or after about 15 min. Vorta would be usable but the user would wonder about the random timing of catching-up backups.

https://github.com/borgbase/vorta/blob/f76aa5a5f483b776084dccb5199098154f4b7279/src/vorta/scheduler.py#L235-L250

**Comment by real-yfprojects** [comment]
Pausing the scheduler might also be applicable in other cases and allowing the user to pause manually might makeup for a good feature as well.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Then let's add it and maybe refactor the Scheduler, when it's been in use for a while.

**Pull request merged**
