### PR TITLE
Improve flatpak

### PR DESCRIPTION
**Pull request by Hofer-Julian**
This PR updates the flatpak dependencies and some refactoring.
It will allows to build Vorta with GNOME Builder with only one click.
The next step will be to adjust the contribution docs.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
From my side, this PR is ready to be merged.

**Comment by prefixtry** [comment]
Thank you for working on an improvement! Does this improvement even include a solution for the following Flatpak related issues https://github.com/borgbase/vorta/issues/316 and https://github.com/borgbase/vorta/issues/315 or https://github.com/borgbase/vorta/issues/318? Or could you imagine integrating solutions into your PR?

**Comment by Hofer-Julian** [comment]
I need a Wayland program in order to close https://github.com/borgbase/vorta/issues/316.
You are very welcome to suggest one in https://github.com/borgbase/vorta/issues/316.

https://github.com/borgbase/vorta/issues/315 is done.

For https://github.com/borgbase/vorta/issues/318 you are very welcome to try (e.g, on a virtual machine) if the problem is still persists and report it to https://github.com/borgbase/vorta/issues/318)

**Comment by m3nu** [comment]
I'll need more time on this. If something crashes right when starting it, there could be more issues. So not merging it.

**Comment by m3nu** [comment]
And do you have someone who can sign off on the Flatpak changes? I can't review those.

**Comment by m3nu** [comment]
`os.fork()` crashes macOS due to https://bugs.python.org/issue33725

```
Traceback (most recent call last):
  File "/Users/manu/.pyenv/versions/3.6.7/envs/vorta/lib/python3.6/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: disk I/O error
```

**Comment by m3nu** [comment]
So here is the issue with your changes:

- You added a new setting in the DB `foreground` and use it, without setting up the database. This will fail in all cases. I don't know how this ended up in there.
- If you init the DB *before* forking, the new process won't be able to use the DB. This is how it is on macOS. I didn't test Linux.

Options to solve this:

1. Remove the new setting `foreground`.
2. Init the database 2x: First for the original process, then for the fork. This works, but not a fan.
3. Remove the background feature and always run in foreground.

**Comment by Hofer-Julian** [comment]
@m3nu i can think of some people. I would have to check out if they are interested in investing time in a non-GNOME project.

**Comment by Hofer-Julian** [comment]
@m3nu regarding the flatpak. All I did was update the dependencies and move from yaml to json. It is also not used by the users. This happens at a separate flathub repository. So if there are problems the effect would be really small.

**Comment by Hofer-Julian** [comment]
@m3nu Thank you. I clearly missed these problems. If you mean with background feature the os.fork part, I would prefer to remove that. It would remove some logic, would make the code a little bit more readable and we wouldn't need to explain new contributors that they need to add the foreground option in order to debug Vorta.

Otherwise 2, because the foreground setting was implemented in order to use Vorta intuitively on systems without system tray and I would rather not remove it.

**Comment by m3nu** [comment]
All for removing the option. Most people seem to need it in foreground anyways (macOS, Flatpak, Systemd?). So just having a `--background` option for special cases seems sensible.

Let's make a new PR for it. Can you just keep the Flatpak stuff in this PR and I do another one for the foreground stuff.

**Comment by Hofer-Julian** [comment]
Yes, I will do some cherry-picking and force push to this branch.

**Comment by Hofer-Julian** [comment]
I reduced this PR to the flatpak-specific commits and the flatpak still builds without problems.

**Comment by m3nu** [comment]
I can't test it, but if you're confident to go ahead, let's merge it.

**Comment by Hofer-Julian** [comment]
Yes, let's merge it.

**Comment by m3nu** [comment]
Not sure about the macOS test issue. This used to happen with parallel tests, which are disabled already. Will try to debug this.

**Comment by Hofer-Julian** [comment]
@m3nu thanks!

**Comment by m3nu** [comment]
The error occurs only when it's forked (getting renderer errors). Suggest to merge this and then remove the default forking as discussed.

**Pull request merged**
