### PR TITLE
Force fusion style on Linux

### LINKED ISSUE #298: Problem with QToolbox
Today I tried to find the root of the problem with Vorta's Toolbox (no Text is displayed).
QDesigner gave me an idea, but in the end I couldn't fix it.
Vorta-Adwaita-Problem

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Fixes #298.

I mean the optimal case would be if the Adwaita-like style would work, but it is better than nothing.

### CODE REVIEW

**Comment by m3nu** [comment]
Would this do the same?

```
app = QApplication([])  # wherever we init the app
app.setStyle('Fusion')
```

**Comment by Hofer-Julian** [comment]
> Would this do the same?
> 
> ```
> app = QApplication([])  # wherever we init the app
> app.setStyle('Fusion')
> ```

Yes,  I changed it to your suggestion.

**Comment by geckolinux** [comment]
Hi, would it  be possible to make this forced Fusion theme optional? I use the last Plasma / KDE libs on openSUSE Tumbleweed, and Qt5 apps always integrate just fine with my Qt and Plasma configuration. Thanks!

**Comment by Hofer-Julian** [comment]
What exactly is your problem with the fusion-style?

**Comment by geckolinux** [comment]
Just the fact that it doesn't fit in with my configured widget scheme. Was there a specific reason for hard-coding Fusion into Vorta? It's true that KDE and Qt apps have a lot of variables and most people have trouble getting a consistent look. But it _can_ be done with a bit of effort, and usually those who have gone through the trouble of doing so don't really like it when apps don't respect their system configuration.

Here's an example of a Qt5 app that respects my KDE and Qt themes, alongside a native KDE app:
Screenshot_20200118_231811

**Comment by m3nu** [comment]
We used the fusion style because it avoided some UI issues. If those issues are gone in newer Qt versions, then a PR to change that will be welcome.

**Comment by geckolinux** [comment]
I tried to force the theme using the `QT_QPA_PLATFORMTHEME` variable, but it doesn't fully change it. Is there any other way to change it at run time to test?

**Comment by m3nu** [comment]
The best way to test is probably to comment out that part in the [code](https://github.com/borgbase/vorta/blob/329f096fb4bae8552728ee076b514eb8c43258eb/src/vorta/qt_single_application.py#L21) and then run it from the Git repo following our [dev-instructions](https://vorta.borgbase.com/contributing/).

(Or quick and dirty: edit the file in `site-packages` of the Python installation)

**Comment by geckolinux** [comment]
> (Or quick and dirty: edit the file in site-packages of the Python installation)

Ah yes, good idea. Seems to work just fine with Breeze widgets and my custom color scheme:

Screenshot_20200119_122655

**Comment by Hofer-Julian** [comment]
We currently force fusion style, because there are problems on GNOME based distributions.

**Comment by geckolinux** [comment]
I'll try to give it a shot on another distro. Would it be best to test on Gnome proper, or Cinnamon too?

**Comment by Hofer-Julian** [comment]
GNOME should be enough, thanks

**Pull request merged**
