### PR TITLE
Add custom options to borg create command

### LINKED ISSUE #274: Add custom options to borg create command
I'm looking to add additional arguments to the borg create command from within Vorta, for example, two simple examples:
--exclude-caches
--files-cache=ctime,size

I see there are additional arguments that can be passed while initializing a new repository under the Advanced tab, but my understanding is that there is no current way to add arguments to the "create" command.

This would be (somewhat) similar to issue #96 

I believe this could extend the functionality of Vorta quite a bit in a somewhat general way.

Thanks.

### LINKED ISSUE #561: OSError: [Errno 107] Transport endpoint is not connected
**Describe the bug**
Cannot make backups at all. After working flawlessly, it now gives the above message every time. Confirmed that the remote location is accessible; can mount via `sshfs`, view files including the Borg repository.

**To Reproduce**
1. Click on 'start backup'

**Desktop (please complete the following information):**
  Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-9-amd64
      Architecture: x86-64

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
````
2020-07-28 18:12:35,737 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-07-28 18:12:35,774 - asyncio - DEBUG - Using selector: EpollSelector
2020-07-28 18:12:35,811 - root - DEBUG - Found 0 passwords matching repo URL.
2020-07-28 18:12:35,812 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-07-28 18:12:35,867 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg create --list --info --log-json --json --filter=AM -C none .....
2020-07-28 18:12:37,930 - vorta.borg.borg_thread - ERROR - Remote: Borg 0.29.0: exception in RPC call:
2020-07-28 18:12:37,932 - vorta.borg.borg_thread - WARNING - Remote: Traceback (most recent call last):
2020-07-28 18:12:37,932 - vorta.borg.borg_thread - WARNING - Remote: File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 96, in serve
2020-07-28 18:12:37,935 - vorta.borg.borg_thread - WARNING - Remote: TypeError: open() takes from 2 to 5 positional arguments but 7 were given
2020-07-28 18:12:43,800 - vorta.borg.borg_thread - ERROR - Remote: Platform: FreeBSD usw-s007.rsync.net 12.1-RELEASE-p4 FreeBSD 12.1-RELEASE-p4 rsync_12_1 amd64
2020-07-28 18:12:43,801 - vorta.borg.borg_thread - WARNING - Remote: Python: CPython 3.4.3
2020-07-28 18:12:43,801 - vorta.borg.borg_thread - WARNING - Remote: 
2020-07-28 18:12:43,803 - vorta.borg.borg_thread - WARNING - Please note:
2020-07-28 18:12:43,804 - vorta.borg.borg_thread - WARNING - If you see a TypeError complaining about the number of positional arguments
2020-07-28 18:12:43,804 - vorta.borg.borg_thread - WARNING - given to open(), you can ignore it if it comes from a borg version < 1.0.7.
2020-07-28 18:12:43,805 - vorta.borg.borg_thread - WARNING - This TypeError is a cosmetic side effect of the compatibility code borg
2020-07-28 18:12:43,806 - vorta.borg.borg_thread - WARNING - clients >= 1.0.7 have to support older borg servers.
2020-07-28 18:12:43,807 - vorta.borg.borg_thread - WARNING - This problem will go away as soon as the server has been upgraded to 1.0.7+.
2020-07-28 18:12:44,089 - vorta.borg.borg_thread - INFO - Creating archive at "...."
2020-07-28 18:12:44,245 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-07-28 18:12:44,246 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4455, in main
2020-07-28 18:12:44,247 - vorta.borg.borg_thread - WARNING - exit_code = archiver.run(args)
2020-07-28 18:12:44,248 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4387, in run
2020-07-28 18:12:44,250 - vorta.borg.borg_thread - WARNING - return set_ec(func(args))
2020-07-28 18:12:44,251 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 154, in wrapper
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - return method(self, args, repository=repository, **kwargs)
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 556, in do_create
2020-07-28 18:12:44,252 - vorta.borg.borg_thread - WARNING - log_json=args.log_json)
2020-07-28 18:12:44,254 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archive.py", line 292, in __init__
2020-07-28 18:12:44,255 - vorta.borg.borg_thread - WARNING - self.cwd = os.getcwd()
2020-07-28 18:12:44,256 - vorta.borg.borg_thread - WARNING - OSError: [Errno 107] Transport endpoint is not connected
2020-07-28 18:12:44,256 - vorta.borg.borg_thread - WARNING - During handling of the above exception, another exception occurred:
2020-07-28 18:12:44,259 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-07-28 18:12:44,260 - vorta.borg.borg_thread - WARNING - File "/usr/bin/borg", line 11, in <module>
2020-07-28 18:12:44,260 - vorta.borg.borg_thread - WARNING - load_entry_point('borgbackup==1.1.9', 'console_scripts', 'borg')()
2020-07-28 18:12:44,263 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/archiver.py", line 4477, in main
2020-07-28 18:12:44,265 - vorta.borg.borg_thread - WARNING - tb = '%s\n%s' % (traceback.format_exc(), sysinfo())
2020-07-28 18:12:44,265 - vorta.borg.borg_thread - WARNING - File "/usr/lib/python3/dist-packages/borg/helpers.py", line 1636, in sysinfo
2020-07-28 18:12:44,266 - vorta.borg.borg_thread - WARNING - info.append('PID: %d  CWD: %s' % (os.getpid(), os.getcwd()))
2020-07-28 18:12:44,267 - vorta.borg.borg_thread - WARNING - OSError: [Errno 107] Transport endpoint is not connected
````

### PR DESCRIPTION
**Pull request by samuel-w**
Fixes #274 

Fixes #561 indirectly, add `--remote-path borg1` to actually fix

Example output with `--dry-run` in box: 
```
2020-10-03 00:09:29,308 - vorta.borg.borg_thread - INFO - Running command /home/user/Projects/vorta/venv/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,8 --dry-run --exclude-if-present .nobackup /mnt/data/borg-backblaze::PC-PC-backblaze-2020-10-03T00:09:29 /home/user
```

### CODE REVIEW

**Comment by samuel-w** [comment]
Wait, is the create options the same as `extra_borg_arguments`?

**Review by m3nu — CHANGES_REQUESTED** [review]

**Review by m3nu — CHANGES_REQUESTED** [review]
The create command is not being saved correctly and the backup fails if it's not defined due to adding another empty parameter to the Borg command.

```
2021-01-18 19:40:51,916 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg create --list --progress --info --log-json --json --filter=AM -C zstd,8  --exclude-from /var/folders/g0/6wysw4qn6kl38gkv58jgkkfc0000gp/T/tmpamcx_yuh --exclude-if-present .nobackup xxx.repo.borgbase.com:repo::nyx2-2021-01-18T19:40:51 /Users/manu/...
2021-01-18 19:40:52,395 - vorta.borg.borg_thread - WARNING - usage: borg create [-h] [--critical] [--error] [--warning] [--info] [--debug]
2021-01-18 19:40:52,396 - vorta.borg.borg_thread - WARNING - [--debug-topic TOPIC] [-p] [--log-json]
2021-01-18 19:40:52,397 - vorta.borg.borg_thread - WARNING - [--lock-wait SECONDS] [--bypass-lock] [--show-version]
2021-01-18 19:40:52,397 - vorta.borg.borg_thread - WARNING - [--show-rc] [--umask M] [--remote-path PATH]
2021-01-18 19:40:52,398 - vorta.borg.borg_thread - WARNING - [--remote-ratelimit RATE] [--consider-part-files]
2021-01-18 19:40:52,399 - vorta.borg.borg_thread - WARNING - [--debug-profile FILE] [--rsh RSH] [-n] [-s] [--list]
2021-01-18 19:40:52,399 - vorta.borg.borg_thread - WARNING - [--filter STATUSCHARS] [--json] [--no-cache-sync]
2021-01-18 19:40:52,399 - vorta.borg.borg_thread - WARNING - [--no-files-cache] [--stdin-name NAME] [--stdin-user USER]
2021-01-18 19:40:52,401 - vorta.borg.borg_thread - WARNING - [--stdin-group GROUP] [--stdin-mode M] [-e PATTERN]
2021-01-18 19:40:52,401 - vorta.borg.borg_thread - WARNING - [--exclude-from EXCLUDEFILE] [--pattern PATTERN]
2021-01-18 19:40:52,401 - vorta.borg.borg_thread - WARNING - [--patterns-from PATTERNFILE] [--exclude-caches]
2021-01-18 19:40:52,402 - vorta.borg.borg_thread - WARNING - [--exclude-if-present NAME] [--keep-exclude-tags]
2021-01-18 19:40:52,403 - vorta.borg.borg_thread - WARNING - [--exclude-nodump] [-x] [--numeric-owner] [--noatime]
2021-01-18 19:40:52,404 - vorta.borg.borg_thread - WARNING - [--noctime] [--nobirthtime] [--nobsdflags] [--ignore-inode]
2021-01-18 19:40:52,404 - vorta.borg.borg_thread - WARNING - [--files-cache MODE] [--read-special] [--comment COMMENT]
2021-01-18 19:40:52,405 - vorta.borg.borg_thread - WARNING - [--timestamp TIMESTAMP] [-c SECONDS]
2021-01-18 19:40:52,406 - vorta.borg.borg_thread - WARNING - [--chunker-params PARAMS] [-C COMPRESSION]
2021-01-18 19:40:52,407 - vorta.borg.borg_thread - WARNING - ARCHIVE [PATH ...]
2021-01-18 19:40:52,407 - vorta.borg.borg_thread - WARNING - borg create: error: argument ARCHIVE: Invalid location format: ""
```

**Comment by m3nu** [comment]
Placement is great now. but there is an error, when adding more than 2 arguments. That's because Python won't split them.

**Comment by m3nu** [comment]
Thanks for the contribution @samuel-w! Active community members like yourself ensure the quality and relevance of this project.

**Pull request merged**
