### PR TITLE
add option to refresh individual archives

### PR DESCRIPTION
**Pull request by rblenis**
allow individual archives to do a more complete refresh, pulling in/updating size and duration. (see discussion #828)

### CODE REVIEW

**Comment by m3nu** [comment]
Minor comment on renaming the file and class. Rest looks great. Thanks for the useful addition!

**Comment by rblenis** [comment]
Added parsing of repo stats that comes back with the archive results - this provides a solution to issue #338 as well, though doing a 'borg info' after prune and delete should also be added to fully address #338.

**Comment by rblenis** [comment]
@m3nu, what are you suggesting I rename the file and class to?

**Comment by rblenis** [comment]
not sure why checks timed-out. I reran the action in my fork and it completed, but can't figure out how to get it to re-run in the PR unless I push a dummy change.

**Review by m3nu — COMMENTED** [review]
> not sure why checks timed-out. I reran the action in my fork and it completed, but can't figure out how to get it to re-run in the PR unless I push a dummy change.

Some macOS checks can hang *after* the tests were successful. I'm not sure about the reason, but addressed a few possible reasons in #877. Could be the combo of pytest + coverage when using threads.

**Comment by m3nu** [comment]
> @m3nu, what are you suggesting I rename the file and class to?

Usually we name our commands after the Borg subcommand used. In `vorta.borg` we already have:

- `list_archive.py`: list files in an archive
- `list_repo.py`: list archives in a repo
- `info`: list info on a repo

So the consistent choice would be to rename `info.py` to `info_repo.py` and your new module to `info_archive.py`?

**Comment by m3nu** [comment]
The renaming is mostly logistics. I really like this PR because it only changes what's necessary and is easy to understand. If you prefer, I can do the renaming before merging.

**Comment by m3nu** [comment]
Is it OK if I finish the renaming and then just merge?

**Comment by rblenis** [comment]
sure

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Thanks for the contribution. Merged.

**Pull request merged**
