### PR TITLE
Save window state

### PR DESCRIPTION
**Pull request by Hofer-Julian**
- stores window width&height in peewee database before closing
- gets the window state during initialization of MainWindow

### CODE REVIEW

**Comment by m3nu** [comment]
How about using 2 settings, rather than adding more cols? Like `previous_window_width` and `previous_window_height`. That way you don't even need to change the schema.

**Comment by Hofer-Julian** [comment]
Sure, why not.
Do you want to have `previous_profile_id ` moved to this second setting as well?

**Comment by m3nu** [comment]
The settings table has 2 cols to save values currently:

- `value`: the original field for bool
- `value_str`: Added for `previous_profile_id`

You can probably just use `value_str` to save the height and width and typecast it when using.

```
class SettingsModel(pw.Model):
    """App settings unrelated to a single profile or repo"""
    key = pw.CharField(unique=True)
    value = pw.BooleanField(default=False)
    str_value = pw.CharField(default='')
    label = pw.CharField()
    type = pw.CharField()
```

**Comment by Hofer-Julian** [comment]
Okay, I understand what you mean now.
Thought about it as well, but didn't really understand why you've used Strings to store integers in the first place. But let's do it that way!

**Comment by Hofer-Julian** [comment]
@m3nu I think you comments are resolved now.

**Comment by sudwhiwdh** [comment]
What about saving and restoring the window position as well?
Or whether the window is maximized or not.

**Pull request merged**
