### PR TITLE
loglink removed from about and added to Logs

### PR DESCRIPTION
**Pull request by pavankalyan224847**
removed the click to vew logs link from about view  and added it to Logs

#1862

### CODE REVIEW

**Review by pavankalyan224847 — COMMENTED** [review]
I have personally reviewed my changes please review the PR and let me know if any changes have to be made to the PR thank you .

**Comment by m3nu** [comment]
Thanks. I'll run your changes locally and let you know if they are good to merge. Thanks and sorry for the delay.

**Comment by pavankalyan224847** [comment]
That's totally alright thank you for looking into it and please guide me through other issues that i can work on

**Comment by pavankalyan224847** [comment]
Please tell me if the work on this issue is complete so that i can start working on other issues thank you

**Comment by m3nu** [comment]
Just ran this locally. I think the PR does what it aimed for. What I'd change:

- Put the text below the table of repo events. Since it's less important than the table.
- Slightly change text to something like "See here for complete logs". Otherwise the difference between the event table and those logs won't be clear. We could even say "See here for full Borg and Vorta logs" to make it clear output from both is logged there.

**Comment by pavankalyan224847** [comment]
Do you want me to add the above changes ? I would be glad make the above changes through a commit and I have a doubt the changes i have made on my local machine in the feature branch(the one that i pushed ) I am not able to see any changes on my local machine when i run vorta so I was relying only on qt creator inorder to make this PR so can you please tell me how I can run these changes locally so that it would speed up my work thank you

**Comment by m3nu** [comment]
Yes, please add the changes and add a new commit here.

For details on how to make code changes, see here: https://vorta.borgbase.com/contributing/

**Comment by pavankalyan224847** [comment]
Alright I'll make those changes and setup the project again on the local machine i had forked the repo and then cloned probably that was the issue

**Comment by real-yfprojects** [comment]
Try to use the dev mode `vorta --dev`.

**Comment by pavankalyan224847** [comment]
Thank you so much it works

**Comment by real-yfprojects** [comment]
> * Put the text below the table of repo events. Since it's less important than the table.
> 
> * Slightly change text to something like "See here for complete logs". Otherwise the difference between the event table and those logs won't be clear. We could even say "See here for full Borg and Vorta logs" to make it clear output from both is logged there.

Did you already manage to implement those changes? @pavankalyan224847

**Comment by real-yfprojects** [comment]
> no not yet i wasn't able to work on it due to my schedule(college exams) i will make a commit but if this issue requires an immediate fix

No worries.

**Pull request closed without merging**
