### PR TITLE
Use fnmatch for exclude patterns.

### PR DESCRIPTION
**Pull request by real-yfprojects**
The standard exclude pattern used by borg is *fnmatch*. 

* src/vorta/assets/UI/sourcetab.ui : Change `E.g. **/.cache` to `E.g. */.cache`.

* Use fnmatch to exclude files when calculating source stats.

### CODE REVIEW

**Comment by m3nu** [comment]
Thats fantastic and gets rid of them copied Borg code. Results match up too?

**Comment by real-yfprojects** [comment]
> Thats fantastic and gets rid of them copied Borg code. Results match up too?

Yes, but I had to copy some code from borg to make fnmatch matching coherent. And I had to make vorta check whether to include directories which it didn't do before.

**Comment by real-yfprojects** [comment]
Introduced some optimisations.

**Review by m3nu — APPROVED** [review]

**Comment by vraimonds** [comment]
Hello! 👋🏻 

How do I do an inverted exclude now? I'd like to exclude all the files and folders in **~/Library/** folder except for **Keychains** and let's say **Containers**  now. I tried to write a glob pattern ~/Library/!(Keychains|Containers) but it seems to not be working. Previously I had a regex for this, which was working and is not working anymore since this change got introduced.

**Pull request merged**
