### PR TITLE
Keep the profile list sorted when creating/renaming profiles

### LINKED ISSUE #1983: Profile list in the main window are not kept sorted when adding/renaming entries
#### Description

Creating a new profile adds the new profile at the bottom of the list in the main window. Similarly, editing an existing profile doesn't change its position in the list. I think that in both cases the list should be kept sorted. Restarting Vorta correctly updates the positions of the profiles to be sorted alphabetically.

This was recently noticed during the review of https://github.com/borgbase/vorta/pull/1899#issuecomment-2029914025

1. Create a new profile using the menu in the main window
2. The profile is added last on the list, even if it should sort before other entries

Alternatively:
1. Rename an already existing profile
2. Its position in the list doesn't change, even if the new alphabetical ordering is no longer valid

#### Environment

- OS: Linux
- Vorta version: latest commit (9b8dbcecfbab7e7492e05f5e0ae22a2631335718)
- Installed from: pip
- Borg version: N/A

I see two possible solutions for this:

1. Add some additional handling in the `profile_add_edit_result` function to keep the list sorted. This is a quick commit that does that: https://github.com/Parnassius/vorta/commit/59661f937b25670e0bb40362a696693aa01bbf90

2. Use the [sortItems method of QListWidget](https://doc.qt.io/qt-6/qlistwidget.html#sortItems) to sort the list after every update, thus removing the need to use the `order_by` sql method.

The two solutions cannot co-exist since the sql ordering is case-insensitive while QListWidget.sortItems is case-sensitive. In the second case additional care should be taken to ensure the use of `sortItems` doesn't break anything. From a quick glance I think the way `current_profile` is set during the initialization of the main window should be updated, and maybe some additional changes are needed as well. https://github.com/borgbase/vorta/blob/9b8dbcecfbab7e7492e05f5e0ae22a2631335718/src/vorta/views/main_window.py#L66-L68

What do you think? Let me know if I should create a small pull request with the commit linked above or if a solution based on option 2 should be preferred

### PR DESCRIPTION
**Pull request by Parnassius**
### Description

Creating a new profile adds the new profile at the bottom of the list in the main window. Similarly, editing an existing profile doesn't change its position in the list. This change keeps the list sorted alphabetically in both cases.

### Related Issue

Fixes #1983

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by shivansh02** [comment]
Screenshot from 2024-04-12 12-28-37
Works fine for me, assuming we want to keep the sorting case sensitive.

**Comment by m3nu** [comment]
Thanks for testing, @shivansh02! I don't have a strong preference for the case-sensitivity, but would lean towards **case-insensitive** sorting.

**Comment by Parnassius** [comment]
The latest commit adds case-insensitive sorting to the list in the main window, as well as the list in the `Backup Now` tray menu.

The solution I used was to ignore the `ORDER BY` sql directive and simply sort the profiles with python, using both the casefolded and the normal name as the sorting key. Adding the normal name as well is required to keep the sorting stable, otherwise two profiles called `test` and `TEST` would have no fixed ordering.

In my comment on #1983 I talked about the `sortItems` method of `QListWidget`, which would be perfect for the list in the main window. However the tray menu doesn't support anything similar, so I decided against it to keep the logic the same in both places.

One final option I thought about was the [`COLLATE NOCASE`](https://sqlite.org/datatype3.html#collation) sqlite function, but that only converts the 26 ascii uppercase letters to the lowercase equivalents, so the sorting would have remained case-sensitive for non-ascii characters.

**Comment by shivansh02** [comment]
The profile list is now sorted case-insensitively, couldn't test the Backup Now list because my distro doesn't have a tray menu.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Thanks for the contribution, @Parnassius and thanks to @shivansh02 for reviewing.

**Pull request merged**
