### PR TITLE
Initialize the network status monitor lazily

### PR DESCRIPTION
**Pull request by ktosiek**
This avoids problems with `vorta -d` and fork. The problems were mentioned here: https://github.com/borgbase/vorta/issues/629#issuecomment-688998973

### CODE REVIEW

**Review by samuel-w — APPROVED** [review]
Works great, thanks!

**Comment by samuel-w** [comment]
It fixes the no daemon, but now metered networks are not showing up

Result of `dbus-send --print-reply --system --dest=org.freedesktop.NetworkManager "/org/freedesktop/NetworkManager/Settings/1" org.freedesktop.NetworkManager.Settings.Connection.GetSettings`: https://pastebin.com/xmE6q5Hz

**Comment by ktosiek** [comment]
Is that the only "/org/freedesktop/NetworkManager/Settings/X" that `dbus-send --print-reply --system --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/Settings org.freedesktop.NetworkManager.Settings.ListConnections` gives you? This one is an ethernet connection.
I don't have a WiFi card in my current PC, but I'll try testing on real hardware shortly (today/tomorrow).

The "Allowed Network" box only lists WiFi connections, by SSID. This was done to mirror the OSX behaviour, but maybe for NetworkManager it'd be better to show all networks? Expanding that list might not be simple - currently Vorta only looks at the [PrimaryConnection](https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.PrimaryConnection), so some networks (like VPNs) don't make sense on that list.

**Comment by samuel-w** [comment]
It should show all networks, since it is possible to have wired metered internet, such as satellite internet.

**Comment by ktosiek** [comment]
All networks would include things that are not really internet connections though, I've asked on NM IRC and will see if there's a good heuristic we could use. For now you can mark a network as metered in NM settings - Vorta will honour this setting, independently of the networks list.

**Review by m3nu — APPROVED** [review]

**Pull request merged**
