### PR TITLE
Cleanup database at exit, use write-ahead logging

### PR DESCRIPTION
**Pull request by samuel-w**
https://www.tutorialspoint.com/sqlite/sqlite_vacuum.htm

### CODE REVIEW

**Review by m3nu — DISMISSED** [review]

**Comment by m3nu** [comment]
We should look into async/await. Maybe some startup tasks can be offloaded.

**Comment by samuel-w** [comment]
Async is apparently slower for databases https://stackoverflow.com/questions/39803746/peewee-and-peewee-async-why-is-async-slower

**Comment by m3nu** [comment]
Is it worth making startup slower for this low-priority task? How about doing it in the background with the scheduler or when closing?

**Comment by samuel-w** [comment]
I moved it so it runs right before exiting.

**Review by m3nu — APPROVED** [review]

**Comment by samuel-w** [comment]
Added write-ahead logging https://www.sqlite.org/wal.html. It speeds up tests a lot, 30 sec to 16 sec.

**Comment by samuel-w** [comment]
Strange. The tests aren't faster in the CI, but they are faster on my local machine. Still useful though.

**Review by m3nu — APPROVED** [review]

**Review by m3nu — APPROVED** [review]

**Pull request merged**
