### PR TITLE
Reduce icon memory usage

### PR DESCRIPTION
**Pull request by samuel-w**
Turns out, Vorta uses over 300 MB of RAM. The reason is super dumb.

The reason is the icons are imported as 1792 by 1792 images. Each one takes 14MB of memory. No one needs that. 128x128 uses no memory at all.

Now its about 163 MB RAM. Much better.

Before:
```
Line #    Mem usage    Increment   Line Contents
================================================
    83    144.2 MiB    144.2 MiB       @profile
    84                                 def set_icons(self):
    85    158.7 MiB     14.5 MiB           self.extractButton.setIcon(get_colored_icon('cloud-download'))
    86    172.6 MiB     13.9 MiB           self.mountButton.setIcon(get_colored_icon('folder-open'))
    87    184.7 MiB     12.1 MiB           self.checkButton.setIcon(get_colored_icon('check-circle'))
    88    197.1 MiB     12.4 MiB           self.deleteButton.setIcon(get_colored_icon('trash'))
    89    197.9 MiB      0.8 MiB           self.diffButton.setIcon(get_colored_icon('stream-solid'))
    90    210.0 MiB     12.1 MiB           self.pruneButton.setIcon(get_colored_icon('cut'))
    91    222.4 MiB     12.4 MiB           self.listButton.setIcon(get_colored_icon('refresh'))
    92    234.5 MiB     12.1 MiB           self.toolBox.setItemIcon(0, get_colored_icon('tasks'))
    93    246.9 MiB     12.4 MiB           self.toolBox.setItemIcon(1, get_colored_icon('cut'))
```

After:
```
Line #    Mem usage    Increment   Line Contents
================================================
    83    119.9 MiB    119.9 MiB       @profile
    84                                 def set_icons(self):
    85    119.9 MiB      0.0 MiB           self.extractButton.setIcon(get_colored_icon('cloud-download'))
    86    133.9 MiB     13.9 MiB           self.mountButton.setIcon(get_colored_icon('folder-open'))
    87    133.9 MiB      0.0 MiB           self.checkButton.setIcon(get_colored_icon('check-circle'))
    88    133.9 MiB      0.0 MiB           self.deleteButton.setIcon(get_colored_icon('trash'))
    89    133.9 MiB      0.0 MiB           self.diffButton.setIcon(get_colored_icon('stream-solid'))
    90    133.9 MiB      0.0 MiB           self.pruneButton.setIcon(get_colored_icon('cut'))
    91    133.9 MiB      0.0 MiB           self.listButton.setIcon(get_colored_icon('refresh'))
    92    133.9 MiB      0.0 MiB           self.toolBox.setItemIcon(0, get_colored_icon('tasks'))
    93    133.9 MiB      0.0 MiB           self.toolBox.setItemIcon(1, get_colored_icon('cut'))
```

### CODE REVIEW

**Comment by m3nu** [comment]
Nice find. 👍 Generally SVG should be a vector image without any fixed size. But it's possible that Qt will rasteriaze it on import.

Do you see any pixelation after this change?

**Comment by samuel-w** [comment]
Not that I can notice, but I'm using a 1080p display, might be different for 4K.

It's actually visible here: https://github.com/borgbase/vorta/issues/207#issuecomment-466653023. That 100MB jump is due to this bug.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
You are brilliant. Nice find!

**Comment by m3nu** [comment]
On macOS memory went form 390 to 140 MB.

**Pull request merged**
