### PR TITLE
Sort profiles in the Backup Now tray menu

### PR DESCRIPTION
**Pull request by Parnassius**
### Description
This sorts the profile names alphabetically in the `Backup Now` item of the tray menu.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Thank you for the work! Why should the profiles be sorted differently from the profile list within Vorta?

**Comment by real-yfprojects** [comment]
> They indeed shouldn't, the list in the main window is already sorted alphabetically, see here:

Thanks, I wasn't aware of that. When testing it wasn't sorted, now I noticed that it actually is, but only after a restart. Additionally the default profile always appears on top.

**Review by real-yfprojects — APPROVED** [review]

**Comment by Parnassius** [comment]
> Thanks, I wasn't aware of that.
Yeah, I should have specified that in the original message, sorry about the confusion.

> but only after a restart.
It seems that newly created profiles are indeed always added at the bottom of the list, I could try to tackle that in another PR in the next few days.

> Additionally the default profile always appears on top.
It does that for you? I'm unable to test this branch right now, but for me on the latest release (0.9.1) it is sorted like any other profile. Note that the sorting is case-sensitive, could it be that your other profiles start with lower case letters?

**Comment by real-yfprojects** [comment]
> Note that the sorting is case-sensitive, could it be that your other profiles start with lower case letters?

I see, that is indeed the reason. Despite coding for many years I wasn't aware that `"D" < "a"` is true.

**Pull request merged**
