### PR TITLE
More reliable cancel (WIP)

### LINKED ISSUE #332: UI hanging when cancelling a running backup
Start a backup manually, then cancel it. The UI freezes, and the borg process is defunct (zombie, not waited by the parent process)

This occurs on archlinux, using 0.6.21

Please tell me if you need logs.

Regards

### PR DESCRIPTION
**Pull request by m3nu**
Maybe fixes #332

### CODE REVIEW

**Comment by m3nu** [comment]
The feature worked well locally. Just had one idea on how to simplify it:

Instead of having another window to select 2 archives, why not select them on the first screen. And if a user clicks "Diff" without selecting 2 archives, it says "First select two archives using Ctrl or Cmd."

**Comment by sudwhiwdh** [comment]
What does it take from your side to solve this open request?

And is there something like a roadmap to Vorta 0.7?

**Comment by m3nu** [comment]
> What does it take from your side to solve this open request?
> 
> And is there something like a roadmap to Vorta 0.7?

We follow semantic versioning, so 0.7 would need some radical new features. I don't see those yet and will focus on incremental fixes.

For this PR, I can't reproduce the error for now.

**Comment by sudwhiwdh** [comment]
> We follow semantic versioning, so 0.7 would need some radical new features. I don't see those yet and will focus on incremental fixes.

What do you mean "incremental fixes"?
Would https://github.com/borgbase/vorta/issues/317 be such a major change?

> For this PR, I can't reproduce the error for now.

Does that mean this PR should be discarded?
Or does it still bring improvements?

**Pull request merged**
