### PR TITLE
fix some italian translations

### PR DESCRIPTION
**Pull request by paolobenve**

### CODE REVIEW

**Comment by m3nu** [comment]
Thanks for the contribution!

Usually those are edited on Transifex. Need to see how to get them in there.

**Comment by paolobenve** [comment]
where is the explication about vorta translations?

**Comment by m3nu** [comment]
Added you on Transifex.

**Comment by m3nu** [comment]
Guide is here: https://vorta.borgbase.com/contributing/translations/

**Comment by paolobenve** [comment]
how do I see the context in transifex? sometimes you cannot translate without seeing the source code

**Comment by m3nu** [comment]
Screenshot 2023-01-31 at 15 32 24

**Comment by paolobenve** [comment]
ok, but I must
- select the file name with its path
- in some way get the file with nautilus/thunar (requires various steps)
- open it and look for the given line

I was wondering if the platform can show me those lines of the file

**Comment by paolobenve** [comment]
I haven't the Edit Context button... why?

**Comment by real-yfprojects** [comment]
Can this issue be closed? Have to updated the strings changed in this PR?

> ok, but I must
> 
>     * select the file name with its path
> 
>     * in some way get the file with nautilus/thunar (requires various steps)
> 
>     * open it and look for the given line
> 
> 
> I was wondering if the platform can show me those lines of the file

That is how it is. Many IDEs like VS Code make this more easy.

> I haven't the Edit Context button... why?

You don't have admin permissions.

**Pull request closed without merging**
