### PR TITLE
Add desktop file installation button (Linux only)

### PR DESCRIPTION
**Pull request by samuel-w**
Replacement of #564, closed due to complexity and possibly breaking Debian packaging guidelines

I moved the icons because otherwise it would be out of the scope of the package.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
I don't really see what icon copying has to do with autostart. Could you please elaborate?

**Comment by samuel-w** [comment]
The desktop file has a line `Icon=com.borgbase.Vorta`. Normally a user would have to manually copy the icon. This automates that process, along with adding the icon for notifications.

**Comment by Hofer-Julian** [comment]
But this code would:
- be only called when you change autostart settings
- be called every time you change autostart settings.

**Comment by samuel-w** [comment]
Changed it so now:
Autostart functionality is same as before
New button copies desktop file and icons.

**Comment by Hofer-Julian** [comment]
I appreciate your efforts. But I think we should either find a different way than doing this manually during runtime or just accepting that people who use pip directly have to do some extra work. I currently tend towards the latter 😊

**Comment by samuel-w** [comment]
Yeah, I'm going to go with copying things manually, since if a user is using pip its safe to assume they have command line knowledge.

**Pull request closed without merging**
