### PR TITLE
Borg v1.2.2 support. By @real-yfprojects

### PR DESCRIPTION
**Pull request by m3nu**
Cherry picks https://github.com/borgbase/vorta/pull/1434 for 0.8.8 release #1443

### CODE REVIEW

**Comment by m3nu** [comment]
We need to be careful to check for higher version features first in the future. E.g. `V2` > `V122`. Since the compat feature was more built for specific features than subtle changes like this.

**Review by real-yfprojects — APPROVED** [review]
I signed (verified) the commits.

**Comment by real-yfprojects** [comment]
However I would rather merge #1434.

**Comment by m3nu** [comment]
Happy to merge your own.

**Pull request closed without merging**
