### PR TITLE
Fix/loglink moved below logs table

### PR DESCRIPTION
**Pull request by shivansh02**
Moved the complete logs link from about tab to below logs table.
### Description

Removed the link from about tab and added it below logs table on the schedule tab.
### Related Issue

#1862 
### Motivation and Context

Schedule->Logs is a better location for the link, so that one can view the complete logs in case the ones in the summary aren't enough.
### How Has This Been Tested?

Tested by me locally.
### Screenshots (if appropriate):
Screenshot from 2024-02-17 19-47-53
Screenshot from 2024-02-17 19-47-41

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by real-yfprojects** [comment]
Maybe keep the link also in the about tab for backwards compatibility?

**Comment by shivansh02** [comment]
Added the link back to the about tab, please take a look.

**Comment by m3nu** [comment]
Didn't run it locally, but looks fine. Also doesn't change up all the UI files. Will merge tomorrow after testing locally.

**Review by m3nu — APPROVED** [review]

**Comment by m3nu** [comment]
Fixes #1862

**Pull request merged**
