### PR TITLE
Handle ctime and mtime diff changes

### LINKED ISSUE #1672: borg diff: Support new `ctime` and `mtime` fields.
## Problem 
With borg `1.2.4` the `ctime` and `mtime` change types where added to `borg diff` output. See borgbackup/borg#7335 and borgbackup/borg#7414. The types of changes aren't currently supported by Vorta's diff output parser. It therefore throws an exception stating exactly that. This was first reported in #1668. 

## Solution
For now it would be sufficient to make the parser understand the new change types without doing anything with them.

- [ ] Add one or two additional (empty) if-cases to https://github.com/borgbase/vorta/blob/9a14f3a97d8fad1f05eb13599d479655b8e35074/src/vorta/views/diff_result.py#L199 handling `ctime` and `mtime`.

## Follow up

- [ ] Open a FR for displaying the new change info when hovering over a changed file in the diff view as suggested by https://github.com/borgbase/vorta/issues/1668#issuecomment-1485826665.

### PR DESCRIPTION
**Pull request by henry-spanka**
Implements *ctime* and *mtime* diff types added in borg 1.2.4.
Resolves #1672

### Description

Added handling for *ctime* and *mtime* diff and will show changes in tooltip in archive diff window.

### Related Issue

https://github.com/borgbase/vorta/issues/1672

### Motivation and Context

Prevents crash on borg >= 1.2.4

### How Has This Been Tested?

Tested on borg 1.2.4 and added tests for handling *ctime* and *mtime*.

### Screenshots (if appropriate):
Screenshot 2023-04-01 at 21 16 47

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by m3nu** [comment]
Looks good.

**Review by real-yfprojects — COMMENTED** [review]
Thank you for taking care of this!

In the following lines I have added change types for each change type known to borg. Although these extra enum items aren't referenced anywhere in the code, I still find them useful as a mapping. 
https://github.com/borgbase/vorta/blob/9824b880941af28d3bb3d6748d538ddf6509ceec/src/vorta/views/diff_result.py#L553-L559
Can you add `MTIME` and `CTIME`?

Borg returns the times in the iso format which are hard to read for humans. In my opinion converting them to a different (possibly localised) format would be better. Reference code:
https://github.com/borgbase/vorta/blob/9824b880941af28d3bb3d6748d538ddf6509ceec/src/vorta/views/extract_dialog.py#L211-L213
https://github.com/borgbase/vorta/blob/9824b880941af28d3bb3d6748d538ddf6509ceec/src/vorta/views/extract_dialog.py#L452

**Comment by henry-spanka** [comment]
Added requested changes
Screenshot 2023-04-02 at 15 50 34

**Review by real-yfprojects — APPROVED** [review]

**Comment by m3nu** [comment]
LGTM and works as promised. Also good tests. Let's wait for @Hofer-Julian, since he originally added this feature.

**Review by Hofer-Julian — APPROVED** [review]
I cannot test the changes at the moment, but they look good to me.

**Comment by real-yfprojects** [comment]
Will do some squashing while preserving the revert commit.

**Review by real-yfprojects — APPROVED** [review]

**Comment by real-yfprojects** [comment]
I am happy that this can be included in our next release. Thanks. Btw when is the next release going to take place @m3nu?

**Pull request merged**
