### PR TITLE
Support for breaking changes in Borg v2

### LINKED ISSUE #1366: BorgBackup v2 conversion
The upcoming version 2 will have a number of breaking changes to clean up more legacy features and code.

 * [ ] ~~`borg transfer` to transition 1.x repositories to the new 2.0 repo format. *Ask user before this irreversible action*~~
 * [ ] scp style repository syntax is gone in favor of `ssh://`. Convert existing URLs in DB?
 * [ ] Handle adding v1 repos with borg v2 installed - and the other way around by showing a constructive error message.
 * [x] Specify repository with new `-r` flag instead of `::` syntax:
   * [x] `prune`
   * [x] `compact`
   * [x] `create`
   * [x] `check`
   * [x] `extract`
   * [x] `mount`
   * [x] `umount`
   * [x] `list`
   * [x] `info`
   * [x] `delete`
 * [x] Specify archive with new positional parameter for most Borg sub-commands instead of `::` syntax.
     * [x] `mount`
     * [x] create
     * [x] extract
     * [x] list
     * [x] delete
     * [x] info
 * [x] Specify archive with `--glob-archives` or `-a` flag with a glob matching multiple archives for certain Borg sub-commands, e.g. `borg delete --glob-archives 'myarchive*'` or `borg recreate --glob-archives 'myarchive*'.
    * [x] mount
    * [x] delete
    * [x] info
 * [x] Replace use of `--prefix` with `--glob-archives`, e.g. `--globarchives 'myprefix*'`.
 * [x] Available encryption algorithms changed.
 * [x] Repository sub-commands have been split off into new commands:
   * [x] `init` -> `rcreate`
   * [x] `list` -> `rlist`
   * [x] `info` -> `rinfo`
 * [x] Other Borg sub-commands may have changed as well. Audit and update:
   * [x] `prune`
   * [x] `compact`
   * [x] `create`
   * [x] `check`
   * [x] `extract`
   * [x] `mount`
   * [x] `umount`
   * [x] `list`
   * [x] `info`
 * [x] `borg compact --cleanup-commits` flag has been removed.
- [x] the --glob-archives option was renamed to --match-archives (the short option name -a is unchanged)
- [x] Add test cases (json) for Borg v2. Way to pass Borg version to tests.

Full changelog: https://borgbackup.readthedocs.io/en/2.0.0b1/changes.html

Discussion tickets: https://github.com/borgbackup/borg/discussions/6952 and https://github.com/borgbackup/borg/discussions/6799.

### PR DESCRIPTION
**Pull request by m3nu**
Fixes #1366

### CODE REVIEW

**Comment by real-yfprojects** [comment]
I cleanup the history of the branch and force push so we can keep a nice history when merging. You are ok with this, @m3nu?

**Comment by m3nu** [comment]
Sounds good!

**Comment by real-yfprojects** [comment]
I squashed all the 'atomic' changes into one commit. For the multi-file changes I left a commit each, so that these can easier be assigned to each other. (And I have a backup of the pre-rebase state.) Can you test this branch, since the merges and rebases can occasionally contain errors?

**Comment by m3nu** [comment]
Perfect! Will do.

**Comment by m3nu** [comment]
Manually tested all adjusted functions, except mounting. Added a small commit with 2 items I noticed.

**Comment by m3nu** [comment]
Tested with Borg 1.2 as well and looks all good. So we should maybe just merge and ship it.

**Comment by real-yfprojects** [comment]
Should squash the latest commit?

**Comment by m3nu** [comment]
Or squash the whole branch? Both fine with me, if you want to preserve commits.

**Comment by real-yfprojects** [comment]
> Or squash the whole branch? Both fine with me, if you want to preserve commits.

I think commits should have a size that allows identifying changes that depend on each other.
[41d2b86](https://github.com/borgbase/vorta/pull/1392/commits/41d2b86f8b2ff36c1438c87b4d644b9a2072db42) contains such changes, while [d16057a](https://github.com/borgbase/vorta/pull/1392/commits/d16057af59747579c39323af1b8c26319af6e4b9) contains changes that are loosely connected between files.

**Comment by m3nu** [comment]
Then the last commit may fit best with [d16057a](https://github.com/borgbase/vorta/pull/1392/commits/d16057af59747579c39323af1b8c26319af6e4b9).

**Comment by real-yfprojects** [comment]
I created [d335077](https://github.com/borgbase/vorta/pull/1392/commits/d3350779c7c5d6e500faac18d85d494ac127b468) instead.

**Review by real-yfprojects — APPROVED** [review]

**Comment by real-yfprojects** [comment]
Ready to merge?

**Comment by m3nu** [comment]
Done! Good job!

**Comment by m3nu** [comment]
Happy to have this covered. I expect some small tweaks after it got widespread use, but good to have it out nontheless.

**Pull request merged**
