### PR TITLE
Use newest translation data from transifex

### PR DESCRIPTION
**Pull request by Hofer-Julian**
I've translated the remaining German strings.

Also Pavel Borecki completely translated Czech.

### CODE REVIEW

**Comment by m3nu** [comment]
Great. Pavel is already a contributor. But for new translators we need to add them to the [contributors file](https://github.com/borgbase/vorta/blob/master/CONTRIBUTORS.md) too.

**Comment by Hofer-Julian** [comment]
Good to know!

So I guess, you and me should be add to German translators?

**Comment by m3nu** [comment]
If you like, sure. No need to add me though. Thomas did most translation work in the beginning.

**Comment by Hofer-Julian** [comment]
If you don't want to be added, I also won't add myself.

**Pull request merged**
