### PR TITLE
feat: add profile name to log messages

### PR DESCRIPTION
**Pull request by diivi**
### Description
Append profile name to every log message

### Related Issue
#1379 

### Motivation and Context
Helps the user know which profile the log is coming from.

### How Has This Been Tested?
image

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] I have read the [CONTRIBUTING](https://vorta.borgbase.com/contributing/) guide.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

*I provide my contribution under the terms of the [license](./../../LICENSE.txt) of this repository and I affirm the [Developer Certificate of Origin][dco].*

[dco]: https://developercertificate.org/

### CODE REVIEW

**Comment by real-yfprojects** [comment]
This would also be useful for the other messages like `Backup finished`.

**Comment by real-yfprojects** [comment]
> I did this for `logText` (the second one) only, should I do it for the first one too, i.e. `progressText` (all occurences of `backup_progress_event.emit`)?

Yes, since currently one has no way to tell which backup has finished.

**Comment by diivi** [comment]
> Yes, since currently one has no way to tell which backup has finished.

So why not do this just for the Backup Finished message instead of every progress event?
Sorry, don't have much context about long running background backups.

**Comment by real-yfprojects** [comment]
> So why not do this just for the Backup Finished message instead of every progress event?

Doesn't it also apply to other progress messages? None of them state the profile they are originating from.

**Comment by diivi** [comment]
Hey, I need some help understanding how I can get the profile name in the various jobs in vorta. For example the create job:

```python
    def process_result(self, result):
```
Should I access `result[params][profile_name]` to get the profile name?
Also, what about the functions which have a signature like this: (no result)
```
    def started_event(self):
```
How do I get the profile name to display in the progress event emitted by these functions?
Or should I skip these?

**Comment by real-yfprojects** [comment]
This could be cleaner and better but you can always access the profile from a BorgJob with 
```py
self.params['profile_id']
```

**Comment by real-yfprojects** [comment]
I think you have to resolve the merge conflicts before the tests are run.

**Review by real-yfprojects — APPROVED** [review]
I don't know a better way to use the same message template over and over again with a qt signal -- besides maybe writing a function.

**Pull request merged**
