### PR TITLE
Fix for  #1016

### PR DESCRIPTION
**Pull request by bastiencyr**
Hello, 
Folders and files are correctly sorted without error and regression :)

### CODE REVIEW

**Comment by m3nu** [comment]
Thanks for the quick fix!

**Comment by Hofer-Julian** [comment]
Can we make a bugfix release for that? 
Alternatively I can just release the latest master on flathub.

**Comment by m3nu** [comment]
Yes, I was planning that. I also want to undo the PyQt version limit from #1011 , since it only affects Pyinstaller and isn't needed for other install options.

**Comment by Hofer-Julian** [comment]
Thanks!

**Pull request merged**
